project:
  type: website
  output-dir: docs

website:
#  title: "Fish-MIP"
  image: "logo_test.png"
  navbar:
    background: primary
    logo: "logo_test.png"
    left:
      - href: index.qmd
        text: Home
      - text: Approach
        file: about.qmd
      - text: Protocols
        file: protocols.qmd
      - text: Publications
        file: publications.qmd
      - text: Models and Members
        file: models_members.qmd
      - text: Data Tools
        file: tools.qmd
      - text: Events
        file: events.qmd
      - text: Blog
        file: blogs.qmd
   
    right:
    - icon: twitter
      href: https://twitter.com/fishmip
    - icon: github
      href: https://github.com/Fish-MIP
      
      


        
        

        
        

        
      


format:
  html:
    theme: sandstone
    css: styles.css
    toc: false