project:
  type: website
  output-dir: docs

website:
#  title: "Fish-MIP"
  #image: "logo_test.png"
  navbar:
    background: primary
    logo: "one_line_colour_logo.png"
    right:
      - href: index.qmd
        text: Home
      - text: Approach
        href: about.qmd
      - text: People
        menu: 
          - text: Science Coordination Group
            href: sciencegroup.qmd
          - text: Working Groups
            href: workinggroups.qmd
          - text: Modelling Teams
            href: modellingteams.qmd
     # - text: Models
     #   menu: 
     #     - text: Global
     #       href: globalmodels.qmd
     #     - text: Regional
     #       href: regionalmodels.qmd
        #file: models.qmd
      - text: Protocols
        href: protocols.qmd
      - text: Publications
        href: publications.qmd
      # - text: Data
      #   menu: 
      #     - text: Outputs
      #       href: outputs.qmd
      #     - text: Tools
      #       href: tools.qmd
      - text: Data
        href: tools.qmd
      - text: News
        menu: 
          - text: Events
            href: events.qmd
          - text: Blog
            href: blogs.qmd
      - icon: twitter
        href: https://twitter.com/fishmip
        target: _blank
      - icon: github
        href: https://github.com/Fish-MIP
        target: _blank
  page-footer:
      background: "#9FD0D7" 
      left:  Copyright &copy; 2023 [Fish-MIP](https://github.com/Fish-MIP)
      right: "Built using [Quarto](https://quarto.org/)"
      
format:
  html:
    theme: custom.scss
    #css: styles.css
    toc: false
    editor: visual
    