project:
  type: website
  output-dir: docs

website:
  title: "FishMIP"
  navbar:
    background: primary
    left:
      - href: index.qmd
        text: Home
      - href: approach.qmd
        text: Approach

        
      


format:
  html:
    theme: journal
    css: styles.css
    toc: false