project:
  type: website
  output-dir: docs

website:
#  title: "Fish-MIP"
  #image: "logo_test.png"
  navbar:
    background: primary
    logo: "one-line-colour-logo_transparent_background.png"
    right:
      - href: index.qmd
        text: Home
      - text: Approach
        href: about.qmd
      - text: People
        href: models_members.qmd
      - text: Models
        file: models.qmd
      - text: Protocols
        href: protocols2.qmd
      - text: Publications
        href: publicationsv2.qmd
      - text: Data Tools
        href: tools.qmd
      - text: News
        menu: 
          - text: Events
            href: events.qmd
          - text: Blog
            href: blogs.qmd
      - icon: twitter
        href: https://twitter.com/fishmip
      - icon: github
        href: https://github.com/Fish-MIP
      
format:
  html:
    theme: custom.scss
    #css: styles.css
    toc: false
    editor: visual