project:
  type: website
  output-dir: docs

website:
#  title: "Fish-MIP"
  #image: "logo_test.png"
  navbar:
    background: primary
    logo: "one_line_colour_logo.png"
    right:
      - href: index.qmd
        text: Home
      - text: Approach
        href: about.qmd
      - text: People
        menu: 
          - text: Science Coordination Group
            href: sciencegroup.qmd
          - text: Working Groups
            href: workinggroups.qmd
          - text: Modelling Teams
            href: modellingteams.qmd
      - text: Models
        menu: 
          - text: Global
            href: globalmodels.qmd
          - text: Regional
            href: regionalmodels.qmd
        #file: models.qmd
      - text: Simulations
        href: simulations.qmd
      - text: Publications
        href: publicationsv2.qmd
      - text: Data
        menu: 
          - text: Outputs
            href: outputs.qmd
          - text: Tools
            href: tools.qmd
      - text: News
        menu: 
          - text: Events
            href: events.qmd
          - text: Blog
            href: blogs.qmd
      - icon: twitter
        href: https://twitter.com/fishmip
      - icon: github
        href: https://github.com/Fish-MIP
  page-footer:
      background: "#9FD0D7" 
      left:  Copyright &copy; 2023 [Fish-MIP](https://github.com/Fish-MIP)
      right: "Built using [Quarto](https://quarto.org/)"
      
format:
  html:
    theme: custom.scss
    #css: styles.css
    toc: false
    editor: visual