project:
  type: website
  output-dir: docs

website:
#  title: "Fish-MIP"
  #image: "logo_test.png"
  navbar:
    background: primary
    logo: "one-line-colour-logo_transparent_background.png"
    left:
      - href: index.qmd
        text: Home
      - text: Approach
        file: about.qmd
      - text: People
        file: models_members.qmd
      - text: Models
        file: models.qmd
      - text: Protocols
        file: protocolsv2.qmd
      - text: Publications
        file: publicationsv2.qmd
      - text: Data Tools
        file: tools.qmd
      - text: News
        menu: 
          - text: Events
            href: events.qmd
          - text: Blog
            href: blogs.qmd
   
    right:
    - icon: twitter
      href: https://twitter.com/fishmip
    - icon: github
      href: https://github.com/Fish-MIP
      
  
        
        

        
      


format:
  html:
    theme: [sandstone, custom.scss]
    #css: styles.css
    toc: false
    editor: visual