project:
  type: website
  output-dir: docs

website:
  image: /FishMIP_assets/one_line_colour_logo.png
  favicon: /FishMIP_assets/one line logo/pngs/one-line-colour-logo_transparent_background.png
  navbar:
    background: primary
    logo: FishMIP_assets/one_line_colour_logo.png
    logo-alt: FishMIP Home
    logo-href: /index.html
    collapse-below: lg
    right:
      - href: index.qmd
        text: Home
      - text: Approach
        href: pages/about.qmd
      - text: People
        menu: 
          - text: Science Coordination Group
            href: pages/sciencegroup.qmd
          - text: Modelling Teams
            href: pages/modellingteams.qmd
          - text: Working Groups
            href: pages/workinggroups.qmd
      - text: Protocols
        href: pages/protocols.qmd
      - text: Publications
        href: pages/publications.qmd
      - text: Data & Tools
        href: pages/tools.qmd 
      - text: News
        menu: 
          - text: Events
            href: pages/events.qmd
          - text: Blog
            href: pages/blogs.qmd
      - text: Join us
        href: pages/joinus.qmd
      - icon: bluesky
        href: https://bsky.app/profile/fishmarinemip.bsky.social
        target: _blank
      - icon: linkedin
        href: https://www.linkedin.com/company/fisheries-and-marine-ecosystem-model-intercomparison-project-fishmip
        target: _blank
      - text: '{{< iconify fa7-brands:google-scholar style="color:#00165A;" >}}'
        href: https://scholar.google.com/citations?hl=en&user=qC76LesAAAAJ&view_op=list_works&sortby=pubdate
        target: _blank
      - icon: github
        href: https://github.com/Fish-MIP
        target: _blank
        
     # Not currently in use:
     # - text: Models
     #   menu: 
     #     - text: Global
     #       href: globalmodels.qmd
     #     - text: Regional
     #       href: regionalmodels.qmd
        #file: models.qmd
      #    - text: Outputs
      #      href: outputs.qmd
       #   - text: Tools
        #    href: tools.qmd
      #    - text: Input Explorer 
      #      href: datatools/interactivetool.qmd
      #    - text: Country level outputs
      #      href: datatools/inputexplorer.qmd
       #   - text: Tutorials
        #    href: datatools/tutorials.qmd
      #    - text: Terms of Use
        #    href: datatools/termsofuse.qmd
  page-footer:
      background: primary
      left: "<img src='/FishMIP_assets/UN_OceanDecadeLogo.png' alt='UN Ocean Decade Logo' style='height: 7.5em; vertical-align: middle;'>"
      center: "<br>Copyright &copy; 2023 [Fish-MIP](https://github.com/Fish-MIP)"
      right: "Built using [Quarto](https://quarto.org/)<br>Report website issues [here](https://github.com/Fish-MIP/Fish-MIP.github.io/issues)"

format:
  html:
    theme: custom.scss
    toc: false
    editor: source
    page-layout: full
    anchor-sections: false
    # grid:
    #   sidebar-width: 350px
