---
title: "Models and Members"
editor: visual
---

# Models and members

For a comprehensive list of models and contact details please consult [ISIMIP Impact Models](https://www.isimip.org/impactmodels/).

### CURRENT FISH-MIP MODELS:

------------------------------------------------------------------------

**Global:**

ApeCOSM

BOATS

DBEM

DPBM

EcoOcean

EcoTroph

FEISTY

Macroecological

SS-DBEM

**Regional:**

Atlantis

Ecopath

OSMOSE

mizer

### CURRENT FISH-MIP MEMBERS:

------------------------------------------------------------------------

Manuel Barange (FAO, Italy)

Nicolas Barrier (IRD, France)

Daniele Bianchi (UCLA, US)

Julia Blanchard (University of Tasmania, Australia)

Laurent Bopp (IPSL, France)

Daniel Boyce (Dalhousie University, Canada)

Andrea Bryndum-Buchholz (Memorial University of Newfoundland and Labrador, Canada)

Cathy Bulman (CSIRO, Australia)

William Cheung (UBC, Canada)

Villy Christensen (UBC, Canada)

Marta Coll (ICM-CSIC, Spain)

David Carozza (UQAM, Canada)

Tyler Eddy (Memorial University of Newfoundland and Labrador, Canada)

Jason Everett (University of Queensland, Australia)

Jose Fernandes (AZTI, Spain)

Beth Fulton (CSIRO, Australia)

Eric Galbraith (McGill, Canada)

Didier Gascuel (Agrocampus Ouest, France)

Jerome Guiet (UCLA, US)

Cheryl Harrison (University of Texas Rio Grand Valley, US)

Ryan Heneghan (Universitat Autonoma de Barcelona, Spain)

Alistair Hobday (CSIRO, Australia)

Simon Jennings (PML, UK)

Miranda Jones (UBC, Canada)

Isaac Kaplan (NOAA, US)

Lester Kwiatkowski (CNRS, France)

Patrick Lehodey (CLS, France)

Jason Link (NOAA, US)

Heike Lotze (Dalhousie University, Canada)

Chris Lynam (CEFAS, UK)

Olivier Maury (IRD, France)

Susa Niiranen (Stockholm Resilience Centre, Sweden)

Ricardo Oliveros-Ramos (IATTC, US)

Kelly Ortega-Cisneros (Rhodes University, South Africa)

Colleen Petrik (Texas A&M)

Hubert du Pontavice (Agrocampus Ouest, France)

Jonathan Reum (NOAA, US)

Anthony Richardson (CSIRO, Australia)

Lynne Shannon (University of Cape Town, South Africa)

Yunne-Jai Shin (IRD, France)

Tiago Silva (CEFAS, UK)

Jeroen Steenbeek (Ecopath International Initiative, Spain)

Derek Tittensor (Dalhousie University, Canada)

Nicola Walker (CEFAS)

James Watson (Oregon State University, US)

Phoebe Woodworth-Jefcoats (NOAA, US)
