---
title: "Science Coordination"
---

All FishMIP activities and simulation experiments are designed and led by a dedicated group of coordinators. For general inquiries please contact us on [fishmip.coordinators\@gmail.com](mailto:fishmip.coordinators@gmail.com){.email-link}

For more specific help or requests you may wish to contact the relevant coordinator(s) below:

#### **The FishMIP Coordination Team:**

**FishMIP overall lead:** [Julia Blanchard](mailto:julia.blanchard@utas.edu.au){.email-link}, IMAS- University of Tasmania

**Global Marine Ecosystem Models and Fisheries Data:** [Camilla Novaglio](mailto:camilla.novaglio@leibniz-zmt.de){.email-link}, The Leibniz Centre for Tropical Marine Research (ZMT), and [Ryan Heneghan](mailto:r.heneghan@griffith.edu.au){.email-link}, Griffith University

**Regional Marine Ecosystem Models and Downscaling:** [Kelly Ortega Cisneros](mailto:kelly.ortegacisneros@uct.ac.za){.email-link}, University of Cape Town

**Earth System Models:** [Colleen Petrik](mailto:colleenpetrik@gmail.com){.email-link}, Scripps Institute of Oceanography and [Cheryl Harrison](mailto:chsharrison@gmail.com){.email-link}, Louisiana State University

**Future Societal Scenarios:** [Olivier Maury](mailto:olivier.maury@ird.fr){.email-link} IRD; [Tyler Eddy](mailto:Tyler.Eddy@mi.mun.ca){.email-link}, Marine Institute Memorial University; [Derek Tittensor](mailto:derek.tittensor@dal.ca){.email-link}, Dalhousie University

**Science communication and outreach:** [Andrea Bryndum-Buchholz](mailto:andrea.buchholz@mi.mun.ca){.email-link}, Marine Institute Memorial University and [Kelsey Roberts](mailto:kroberts3@lsu.edu){.email-link}, Louisiana State University

**Data scientist:** [Denisse Fierro-Arcos](mailto:lilian.fierroarcos@utas.edu.au){.email-link}, IMAS-University of Tasmania

**Website:** [Sowdamini Sesha Prasad](mailto:sowdamini.seshaprasad@utas.edu.au){.email-link}, IMAS-University of Tasmania

**ISIMIP cross-sectoral studies:** [Julia Blanchard](mailto:julia.blanchard@utas.edu.au){.email-link} & [Tyler Eddy](mailto:Tyler.Eddy@mi.mun.ca){.email-link}

##### Previous Fish-MIP leadership:

-   **Derek Tittensor** (lead coordinator, 2017-2020)

-   **Eric Galbraith** (global model coordinator, 2014-2020)

-   **Heike Lotze** (lead coordinator, 2014-2016)

-   **Tyler Eddy** (regional model coordinator, 2014-2023)

-   **William Cheung** (global model coordinator, 2014-2016)
