---
title: "ISIMIP 3a"
date: 06/02/2023
categories: 
---

The **goal** of the FishMIP Model Evaluation Protocol \[3a\] is to understand and reduce uncertainty associated with FishMIP models through model evaluation under historical climate and fishing effort forcings.

\
This information will allow FishMIP to better target policy initiatives such as IPCC and IPBES by providing more robust uncertainty assessment, as well as advancing the state of FishMIP models for informing vulnerability, impact, and adaptation plans of coastal sea ecosystems and fisheries (requested by the FAO).

\
The focus of papers produced from this simulation round will be a significant advance in at least two ways:

1.  forcing models with higher spatial resolution global climate models and reconstructed historical fishing effort and

2.  assessment of models against reconstructed historical catches (as well as biomass and other fisheries and ecological metrics in regions where additional data are available).

Uploading simulations by **January 30th 2023** is essential to ensure enough time for analysis and writing of manuscripts in time for submission to the FishMIP 10 Year Anniversary Special Issue planned for 2023. If you are able to upload results sooner, that would be helpful. If you need more time, please let us know as soon as possible.

Progress towards this deadline will be supported and facilitated through monthly global and regional modeller workshops from to:

-   Ensure correct ESM model inputs and access

-   Ensure fishing drivers work (separate global and regional breakaway groups)

-   Tool sharing & troubleshooting

-   Check model outputs/issues

-   Brainstorming and drafting papers (initially methods and preliminary results)

The FishMIP Model Evaluation protocol can be downloaded from [**here**](https://github.com/Fish-MIP/FishMIP_2022_3a_Protocol) while the official ISIMIP3 protocol is located [**on this website**](https://protocol.isimip.org/#ISIMIP3a/marine-fishery_global/marine-fishery_regional).

#### 
