---
date: 05/19/2022
---

**ISIMIP-Proclias cross-sectoral workshop**

The ISIMIP-Proclias cross-sectoral workshop took place 16-19th May 2022. See full summary [here](https://www.isimip.org/outcomes/cross-sectoral-isimip-and-proclias-workshop-2022/).

The workshop was held as a hybrid event and featured a number of plenary and parallel sessions on

-   ISIMIP data and protocols for climate impact modeling ([**PROCLIAS WG 1**](https://proclias.eu/working-groups/wg1))

-   Climate Impact Attribution and Uncertainty Assessment ([**PROCLIAS WG 2**](https://proclias.eu/working-groups/wg2))

-   Cross-sectoral climate impacts ([**PROCLIAS WG 3**](https://proclias.eu/working-groups/wg3))

-   Communication and dissemination of climate impacts ([**PROCLIAS WG 4**](https://proclias.eu/working-groups/wg4)).

Further cornerstones of the workshop were **keynotes by**:

-   **PIK director Johan Rockström (PIK)** "Risks in IPCC AR6 and beyond"

-   **Cath Senior (Met Office)** \"The future direction for CMIP and climate modelling\"

-   **Jakob Zscheischler (UFZ)** \"Progress and challenges in compound event research\"

-   **Camille Parmesan (CNRS, UofP, UofTx)** \"Observed Impacts of Climate Change: From Species to Ecosystem Processes\"

-   **Brian O'Neill (PNNL)** \"Large-scale impact modeling and the Key Risks of climate change\"
