---
pagetitle: Publications | FishMIP
description-meta: |
    Welcome to the Fisheries and Marine Ecosystem Model Intercomparison Project.
---

# Publications

## Peer-reviewed literature

* Bryndum-Buchholz, A., Blanchard, J. L., Coll, M., Pontavice, H. D., Everett, J. D., Guiet, J., Heneghan, R. F., Maury, O., Novaglio, C., Palacios-Abrantes, J., Petrik, C. M., Tittensor, D. P., & Lotze, H. K. (2023). [Applying ensemble ecosystem model projections to future-proof marine conservation planning in the Northwest Atlantic Ocean](https://doi.org/10.1139/facets-2023-0024){target="_blank"}. **FACETS**, 8, 1--16. 

* Novaglio, C., Bryndum-Buchholz, A., Tittensor, D. P., Eddy, T. D., Lotze, H. K., Harrison, C. S., Heneghan, R. F., Maury, O., Ortega-Cisneros, K., Petrik, C. M., Roberts, K. E., & Blanchard, J. L. (2024). [The Past and Future of the Fisheries and Marine Ecosystem Model Intercomparison Project](https://doi.org/10.1029/2023EF004398){target="_blank"}. **Earth’s Future**, 12(9), e2023EF004398.

* Blanchard, J. L., Novaglio, C., Maury, O., Harrison, C. S., Petrik, C. M., Fierro-Arcos, D., Ortega-Cisneros, K., Bryndum-Buchholz, A., Eddy, T. D., Heneghan, R., Roberts, K., Schewe, J., Bianchi, D., Guiet, J., Daniel van Denderen, P., Palacios-Abrantes, J., Liu, X., Stock, C. A., Rousseau, Y., … Tittensor, D. P. (2024). [Detecting, Attributing, and Projecting Global Marine Ecosystem and Fisheries Change: FishMIP 2.0](https://doi.org/10.1029/2023EF004402){target="_blank"}. **Earth’s Future**, 12(12), e2023EF004402. 

* Rynne, N., Novaglio, C., Blanchard, J., Bianchi, D., Christensen, V., Coll, M., Guiet, J., Steenbeek, J., Bryndum-Buchholz, A., Eddy, T. D., Harrison, C., Maury, O., Ortega-Cisneros, K., Petrik, C. M., Tittensor, D. P., & Heneghan, R. F. (2025). [A Skill Assessment Framework for the Fisheries and Marine Ecosystem Model Intercomparison Project](https://doi.org/10.1029/2024EF004868){target="_blank"}. **Earth’s Future**, 13(4), e2024EF004868.

* Eddy, T. D., Heneghan, R. F., Bryndum-Buchholz, A., Fulton, E. A., Harrison, C. S., Tittensor, D. P., Lotze, H. K., Ortega-Cisneros, K., Novaglio, C., Bianchi, D., Büchner, M., Bulman, C., Cheung, W. W. L., Christensen, V., Coll, M., Everett, J. D., Fierro-Arcos, D., Galbraith, E. D., Gascuel, D., … Blanchard, J. L. (2025). [Global and Regional Marine Ecosystem Models Reveal Key Uncertainties in Climate Change Projections](https://doi.org/10.1029/2024EF005537){target="_blank"}. **Earth’s Future**, 13(3), e2024EF005537.

* Cinner, J.E., Thiault, L., Caldwell, I., Ben, J., Blanchard, J.L., Coll, M., Diedrich, A., Eddy, T.D., Everett, J.D., Folberth, C., Gascuel, D., Guiet, J., Gurney, G.G., Heneghan, R., Jägermeyr, J., Jiddawi, N., Lahari, R., Kuange, J., Liu, W., Müller, C., Novaglio, C., Palacios-Abrantes, J., Petrik, C.M., Rabearisoa, A., Steenbeek, J., Tittensor, D.P., Wamukota, A., Pollnac, R. (2022). [The potential impacts of climate change on agriculture and fisheries production in 72 tropical coastal communities](https://doi.org/10.1038/s41467-022-30991-4){target="_blank"}. **Nature Communications**, 13, 11.

* Petrik, C.M., Luo, J.Y., Heneghan, R.F., Everett, J.D., Harrison, C.S., Richardson, A.J. (2022). [**Assessment and constraint of mesozooplankton in CMIP6 Earth system models**.](https://doi.org/10.1029/2022GB007367){target="_blank"} **Global Biogeochemical Cycles**, 36, e2022GB007367.

* Tittensor, D.P., Novaglio, C., Harrison, C.S. et al.,(2021) [**Next-generation ensemble projections reveal higher climate risks for marine ecosystems**](https://doi.org/10.1038/s41558-021-01173-9){target="_blank"}, **Nature Climate Change**, 11, 973--981

* Heneghan, R.F., Galbraith, E., Blanchard, J.L, Harrison, C., Barrier, N., Bulman, C., Cheung, W., Coll, M., Eddy, T.D, Erauskin-Extramiana, M., Everett, J.D., Fernandes-Salvador, J.A., Gascuel, D., Guiet, J., Maury, O., Palacios-Abrantes, J., Petrik, C.M., du Pontavice, H., Richardson, A.J., Steenbeek, J., Tai, T.C., Volkholz, J., Woodworth-Jefcoats, P.A., Tittensor, D.P. (2021). [**Disentangling diverse responses to climate change among global marine ecosystem models**](https://doi.org/10.1016/j.pocean.2021.102659){target="_blank"}. **Progress in Oceanography**, 198.

* Boyce, D. G., Lotze, H. K., Tittensor, D. P., Carozza, D. A., Worm, B. (2020). [**Future ocean biomass losses may widen socioeconomic equity gaps**](https://www.nature.com/articles/s41467-020-15708-9){target="_blank"}. **Nature Communications**, 11:1--11.

* Bryndum-Buchholz, A., Prentice, F., Tittensor, D. P., Blanchard, J. L., Cheung, W. W. L., Christensen, V., Galbraith, E. D., Maury, O. & Lotze, H. K. (2020). [**Differing marine animal biomass shifts under 21st century climate change between Canada's three oceans**](https://doi.org/10.1139/facets-2019-0035){target="_blank"}. **Facets**, 5:105--122.

* Bryndum-Buchholz, A., Boyce, D.G., Tittensor, D.P, Christensen, V., Bianchi, D., & Lotze, H.K. (2020). Climate-change impacts and fisheries management challenges in the North Atlantic\<[https://doi.org/10.3354/meps13438](https://protect-au.mimecast.com/s/Hod0C3Q870Upg4QlzuOEHkD?domain=doi.org){target="_blank"}. **MEPS**, 648:1--17.

* Lotze, H. K., Tittensor, D. P., Bryndum-Buchholz, A., Eddy, T. D., Cheung, W. W. L., Galbraith, E. D., Barange, M., Barrier, N., Bianchi, D., Blanchard, J. L., Bopp, L., Büchner, M., Bulman, C. M., Carozza, D. A., Christensen, V., Coll, M., Dunne, J. P., Fulton, E. A., Jennings, S., Jones, M. C., Mackinson, S., Maury, O., Niiranen, S., Oliveros-Ramos, R., Roy, T., Fernandes, J. A., Schewe, J., Shin, Y.-J., Silva, T. A. M., Steenbeek, J., Stock, C. A., Verley, P., Volkholz, J., Walker, N. D., Worm B. (2019). [**Global ensemble projections reveal trophic amplification of ocean biomass declines with climate change.**](https://www.pnas.org/content/116/26/12907){target="_blank"}. **PNAS**, 116:12907--12912.

* Bryndum-Buchholz, A., Tittensor, D. P., Blanchard, J. L., Cheung, W. W. L., Coll, M., Galbraith, E. D., Jennings, S., Maury, O., Lotze, H. K. (2019). [**Twenty-first century climate change impacts on marine animal biomass and ecosystem structure across ocean basins.**](https://onlinelibrary.wiley.com/doi/abs/10.1111/gcb.14512?af=R){target="_blank"}. **Global Change Biology**, 25:459--472.

* Tittensor, D. P., Eddy, T. D., Lotze, H. K., Galbraith, E. D., Cheung, W., Barange, M., Blanchard, J. L., Bopp, L., Bryndum-Buchholz, A., Büchner, M., Bulman, C. M., Carozza, D. A., Christensen, V., Coll, M., Dunne, J. P., Fernandes, J. A., Fulton, E. A., Hobday, A. J., Huber, V., Jennings, S., Jones, M. C., Lehodey, P., Link, J. S., Mackinson, S., Maury, O., Niiranen, S., Oliveros-Ramos, R., Roy, T., Schewe, J., Shin, Y.-J., Silva, T., Stock, C. A., Steenbeek, J., Underwood, P. J., Volkholz, J., Watson, J. R., Walter, N. D. (2018). [**A protocol for the intercomparison of marine fishery and ecosystem models: Fish-MIP v1.0.**](https://www.geosci-model-dev.net/11/1421/2018/){target="_blank"}. **Geoscientific Model Development**, 11:1421--1442.

* Blanchard, J. L., Watson, R. A., Fulton, E. A., Cottrell, R. S., Nash, K. L., Bryndum-Buchholz, A., Büchner, M., Carozza, D. A., Cheung, W. W. L., Elliott, J., Davidson, L. N. K., Dulvy, N. K., Dunne, J. P., Eddy, T. D., Galbraith, E., Lotze, H. K., Maury, O., Müller, C., Tittensor, D. P., Jennings, S.(2017). [**Linked sustainability challenges and trade-offs among fisheries, aquaculture and agriculture.**](https://www.nature.com/articles/s41559-017-0258-8?mc_cid=afc113a672&mc_eid=5ec9edb8b0){target="_blank"}. **Nature Ecology & Evolution**, 1:1240--1249.

## FishMIP contributions to policy documents

* IPCC, (2022): [**Climate Change 2022: Impacts, Adaptation, and Vulnerability.**](https://doi:10.1017/9781009325844){target="_blank"}. Contribution of Working Group II to the Sixth Assessment Report of the Intergovernmental Panel on Climate Change [H.-O. Pörtner, D.C. Roberts, M. Tignor, E.S. Poloczanska, K. Mintenbeck, A. Alegría, M. Craig, S. Langsdorf, S. Löschke, V. Möller, A. Okem, B. Rama (eds.)]. Cambridge University Press. Cambridge University Press, Cambridge, UK and New York, NY, USA, 3056 pp..

* IPCC (2019). [**IPCC Special Report on the Ocean and Cryosphere in a Changing Climate.**](https://www.ipcc.ch/srocc/home/){target="_blank"}. Pörtner, H. O., Roberts, D. C., Masson-Delmotte, V., Zhai, P., Tignor, M., Poloczanska, E., Mintenbeck, K., Nicolai, M., Okem, A., Petzold, J., Rama, B., Weyer, N. (eds.). IPCC, Geneva, Switzerland.

* IPCC, (2019): [**Climate Change and Land: an IPCC special report on climate change, desertification, land degradation, sustainable land management, food security, and greenhouse gas fluxes in terrestrial ecosystems**](https://www.ipcc.ch/srccl/){target="_blank"}. [P.R. Shukla, J. Skea, E. Calvo Buendia, V. Masson-Delmotte, H.-O. Pörtner, D. C. Roberts, P. Zhai, R. Slade, S. Connors, R. van Diemen, M. Ferrat, E. Haughey, S. Luz, S. Neogi, M. Pathak, J. Petzold, J. Portugal Pereira, P. Vyas, E. Huntley, K. Kissick, M. Belkacemi, J. Malley, (eds.)]. IPCC, Geneva, Switzerland.

* IPBES (2019) [**Global assessment report on biodiversity and ecosystem services of the Intergovernmental Science-Policy Platform on Biodiversity and Ecosystem Services.**](https://ipbes.net/global-assessment){target="_blank"}. Díaz, S., Settele, J., Brondizio E.S., Ngo, H. T. , Guèze, M., Agard, J., Arneth, A., Balvanera, P., Brauman, K. A., Butchart, S. H. M., Chan, K. M. A., Garibaldi, L. A., Ichii, K., Liu, J., Subramanian, S. M., Midgley, G. F., Miloslavich, P., Molnár, Z., Obura, D., Pfaff, A., Polasky, S., Purvis, A., Razzaque, J., Reyers, B., Chowdhury, R. R., Shin, Y.-J., Visseren-Hamakers, I. J., Willis, K. J., Zayas, C. N. (eds.). IPBES secretariat, Bonn, Germany.